# Site settings
title: Self.Reset
header-img: img/home-bg.png
email: dlhopkins2@gmail.com
copyright_name: davidlhopkins
description: > # this means to ignore newlines until "baseurl:"
  Reflections On How I Learned to Love to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  davidlhopkins
learn_profile: davidlhopkins
email_username: dlhopkins2@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
